name: Build lint test deploy\
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: build with dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Run test
        run: npm run test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deplying..."

    